[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rdamsc"
version = "2.1.0"
description = "RDA Metadata Standards Catalog"
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "authlib",
    "dulwich",
    "email_validator",
    "flask",
    "flask-cors",
    "flask-httpauth",
    "flask-login",
    "Flask-OpenID",
    "Flask-WTF",
    "github-webhook",
    "google-auth",
    "passlib",
    "rauth",
    "rdflib",
    "tinydb>=4",
    "tinyrecord>=0.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6",
]

[tool.setuptools]
packages = ["rdamsc"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:'crypt':DeprecationWarning:passlib",
    "ignore:defusedxml.cElementTree:DeprecationWarning:openid",
]
